directories:
  output: release
  buildResources: build
appId: nl.yasas.finch
productName: Finch
electronDist: node_modules/electron/dist
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
mac:
  target: dir
  icon: build/icon.icns
  category: public.app-category.finance
  identity: null
electronVersion: 42.4.0
